### ISSUE TITLE
changing data and colorScale causes error

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-geomap#25]
### Expected Behavior
I should be able to change the data provided to `.data( )` and the associated variable passed to `.colorScale( )` to update the map.

### Current Behavior
Currently, certain combinations will make the map empty.

### Steps to Reproduce (for bugs)
http://jsfiddle.net/14L2qn89/17/

### Your Environment
* Browser Name: Chrome
* Operating System and Version: macOS High Sierra

**Comment by cnavarreteliz** [comment]
@davelandry I think that the root cause of the bug is because we have in the constructor the logic of colorScale. I tested and only render it the first time.

[https://github.com/d3plus/d3plus-geomap/blob/master/src/Geomap.js#L68-L83](https://github.com/d3plus/d3plus-geomap/blob/master/src/Geomap.js#L68-L83)

~~What's your recommendation for to solve it?~~

I found a problem with `topoData` that doesn't resfresh the data with the changes.

**Comment by davelandry** [comment]
It might be a problem with [this](https://github.com/d3plus/d3plus-viz/blob/master/src/_drawColorScale.js) function in d3plus-viz where we set the parameters on `this._colorScaleClass`. In that function you linked, what is it getting for the color value? What is the domain of `this._colorScaleClass` in that usage?

**Comment by cnavarreteliz** [comment]
I'm going to test with `topoData` and if I haven't solutions I'm going to explore in d3plus-viz
